language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t adaoee/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true adaoee/docker-react npm run test
